Script now asks if you want to build the documentation and fails if documentation does not buld or skips if doxygen not present. Updated Travis script for new question and should fail on doxygen fail.

diff --git a/mqc_script b/mqc_script
--- a/mqc_script
+++ b/mqc_script
@@ -577,18 +577,36 @@ if [ $stat -ne 0 ] ; then
     echo "Failure to build"
     exit $stat 
 fi
-command -v doxygen >/dev/null 2>&1
-if [ $? -ne 0 ]; then 
-    echo >&2 "MQCPck requires Doxygen to build documentation but it's not installed.  Skipping." 
-else 
-    ( cat ${MQC_HOME}/doc/Doxyfile ; echo "QUIET=YES" ) | doxygen -
-    if [ $? -ne 0 ]; then 
-	echo "Doxygen failed to build documentation"
-    else
-	echo "Doxygen built documentation"
-    fi 
-fi
 echo "Congratulations! The libmqc is built!"
+
+MQC_BUILD_DOC="g"
+while [ "$MQC_BUILD_DOC" = "g" ]
+do
+    echo "Do you want build the documentation for MQC? [y or n]:"
+    read -n 1 INTERFACE
+    echo ""
+    if [ "$INTERFACE" = "y" ]; then
+	MQC_BUILD_DOC="y"
+    elif [ "$INTERFACE" = "n" ]; then
+	MQC_BUILD_DOC="n"
+    fi
+done
+
+if [ "${MQC_BUILD_DOC}" = "y" ]; then
+    command -v doxygen >/dev/null 2>&1
+    if [ $? -ne 0 ]; then 
+        echo >&2 "MQCPck requires Doxygen to build documentation but it's not installed.  Skipping." 
+    else 
+        ( cat ${MQC_HOME}/doc/Doxyfile ; echo "QUIET=YES" ) | doxygen -
+        stat=$?
+        if [ $stat -ne 0 ]; then 
+    	echo "Doxygen failed to build documentation"
+            exit $stat 
+        else
+    	echo "Doxygen built documentation"
+        fi 
+    fi
+fi
 
 # 
 # Some of the tests run Gaussian.  Find out if the installer wants to run
